// This package provides the procedures used to merge different
// versions of a generated configuration. Usually this is needed when
// you have both updated the YAML outputs and updated the spec file
// containing the definition for how they are generated.
//
// This is like git merge: the idea is to find a common ancestor, then
// find the changes made from that "base" to obtain the resources in
// the working directory ("theirs") and apply those chnges to the
// resources generated by the spec file as modified ("ours").
package merge
